services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.8.0

    ports:
      - ${MEILI_PORT:-7700}:7700

    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL:-debug}
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}

    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped      

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
    
networks:
  meilisearch:
    driver: bridge