name: Extract, Transform, and Load

on:
  workflow_call:
    secrets:
      meilisearch_host:
        required: true
      meilisearch_master_key:
        required: true
      mongodb_url:
        required: true
      mongodb_database:
        required: true
      mongodb_user:
        required: true
      mongodb_password:
        required: true

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
        
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: true

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          check-latest: true
          cache: true
          go-version: 1.22.2
      
      - name: Set Environment Variables from GitHub Secrets
        working-directory: ./etl-go
        run: |
          echo "MEILISEARCH_HOST=${{ secrets.meilisearch_host }}" > .env
          echo "MEILISEARCH_MASTER_KEY=${{ secrets.meilisearch_master_key }}" >> .env
          echo "MONGODB_URL=${{ secrets.mongodb_url }}" >> .env
          echo "MONGODB_DATABASE=${{ secrets.mongodb_database }}" >> .env
          echo "MONGODB_USER=${{ secrets.mongodb_user }}" >> .env
          echo "MONGODB_PASSWORD=${{ secrets.mongodb_password }}" >> .env

      - name: Call Runner Script
        working-directory: ./etl-go
        run: |
          sed -i 's/\r//' runner.sh
          sudo chmod +x runner.sh
          ./runner.sh

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "SHOULD_I_COMMIT=Yes" >> $GITHUB_ENV
          else
            echo "SHOULD_I_COMMIT=No" >> $GITHUB_ENV
          fi
  
      - name: Commit the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        run: |
          git config advice.ignoredHook false
          git config pull.rebase false
          git config --local user.email "action@github.com"
          git config --local user.name "Continuous Deployment"
          git add -A
          git commit -m "cd(etl-go): persist the etl-go program"
          git pull origin main

      - name: Push the changes
        if: ${{ env.SHOULD_I_COMMIT == 'Yes' }}
        uses: ad-m/github-push-action@master
        with:
          # To push to a protected branch, it is essential to utilize a personal access token.
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main
          force_with_lease: true
